// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OooClient is the client API for Ooo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OooClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type oooClient struct {
	cc grpc.ClientConnInterface
}

func NewOooClient(cc grpc.ClientConnInterface) OooClient {
	return &oooClient{cc}
}

func (c *oooClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/mmm.nnn.Ooo/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OooServer is the server API for Ooo service.
// All implementations must embed UnimplementedOooServer
// for forward compatibility
type OooServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedOooServer()
}

// UnimplementedOooServer must be embedded to have forward compatible implementations.
type UnimplementedOooServer struct {
}

func (UnimplementedOooServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedOooServer) mustEmbedUnimplementedOooServer() {}

// UnsafeOooServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OooServer will
// result in compilation errors.
type UnsafeOooServer interface {
	mustEmbedUnimplementedOooServer()
}

func RegisterOooServer(s grpc.ServiceRegistrar, srv OooServer) {
	s.RegisterService(&Ooo_ServiceDesc, srv)
}

func _Ooo_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OooServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mmm.nnn.Ooo/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OooServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ooo_ServiceDesc is the grpc.ServiceDesc for Ooo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ooo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mmm.nnn.Ooo",
	HandlerType: (*OooServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Ooo_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Ooo.proto",
}
