// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JjjClient is the client API for Jjj service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JjjClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type jjjClient struct {
	cc grpc.ClientConnInterface
}

func NewJjjClient(cc grpc.ClientConnInterface) JjjClient {
	return &jjjClient{cc}
}

func (c *jjjClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/hhh.iii.Jjj/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JjjServer is the server API for Jjj service.
// All implementations must embed UnimplementedJjjServer
// for forward compatibility
type JjjServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedJjjServer()
}

// UnimplementedJjjServer must be embedded to have forward compatible implementations.
type UnimplementedJjjServer struct {
}

func (UnimplementedJjjServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedJjjServer) mustEmbedUnimplementedJjjServer() {}

// UnsafeJjjServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JjjServer will
// result in compilation errors.
type UnsafeJjjServer interface {
	mustEmbedUnimplementedJjjServer()
}

func RegisterJjjServer(s grpc.ServiceRegistrar, srv JjjServer) {
	s.RegisterService(&Jjj_ServiceDesc, srv)
}

func _Jjj_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JjjServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hhh.iii.Jjj/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JjjServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Jjj_ServiceDesc is the grpc.ServiceDesc for Jjj service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Jjj_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hhh.iii.Jjj",
	HandlerType: (*JjjServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Jjj_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Jjj.proto",
}
